(set! INST_pt_VOX_guess_pos '(
(tag001 "a" "na" "uma" "sua" "da" "à" )
(tag002 "ser" "maior" "grande" "ter" )
(tag003 "os" "as" "nos" "suas" "seus" "alguns" )
(tag004 "o" "um" "no" "seu" "do" )
(tag005 "se" "ele" "quando" "já" "ela" )
(tag006 "ou" "parte" "cidade" )
(tag007 "é" "foi" "era" "tem" )
(tag008 "mil" "vinte" "quatro" "anos" )
(tag009 "dos" "das" )
(tag010 "mais" "entre" "durante" "apenas" )
(tag011 "ao" "até" "sendo" )
(tag012 "não" "também" "ainda" "eu" )
(tag013 "dois" "três" "cinco" )
(tag014 "e" "que" "como" "mas" "de" "em" "para" "com" "por" "são" )
(tag015 "," "." "!" ";" ":" ")" "(" "{" "}" "[" "]" "-" "=" "\\" "/" "'" "\"" "_" "|" )
))
